#!/usr/bin/env bun
/**
 * Test Lightning Network Payments via Spark Wallet
 * Verifies Lightning invoice generation, payment checking, and balance
 */

import { getTetherWDK } from '../tether-wdk'
import { LightningPaymentProcessor } from '../tether-wdk/lightning-processor'

async function testLightningNetwork() {
  console.log("⚡ Testing Lightning Network via Spark Wallet\n")
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
  
  let wdkManager: any
  let lightningProcessor: LightningPaymentProcessor
  
  try {
    // Step 1: Initialize WDK Manager
    console.log("1️⃣  Initializing Tether WDK with Spark...")
    wdkManager = getTetherWDK()
    console.log("   ✅ WDK initialized")
    
    // Step 2: Initialize Lightning Processor
    console.log("\n2️⃣  Initializing Lightning Payment Processor...")
    lightningProcessor = new LightningPaymentProcessor(wdkManager)
    await lightningProcessor.initialize()
    console.log("   ✅ Lightning processor initialized")
    
  } catch (error) {
    console.error(`   ❌ Error initializing: ${error instanceof Error ? error.message : String(error)}`)
    console.log("\n💡 Common issues:")
    console.log("   • Seed phrase not found (run: bun run generate:wallet)")
    console.log("   • Network connectivity issues")
    console.log("   • Spark wallet not supported on this network")
    return
  }

  try {
    // Step 2.5: Check if user wants to claim a deposit
    const CLAIM_TX_ID = process.env.CLAIM_TX_ID
    if (CLAIM_TX_ID) {
      console.log("\n💰 Claiming Bitcoin deposit...")
      console.log(`   Transaction ID: ${CLAIM_TX_ID}`)
      try {
        const account0 = await wdkManager.getSparkAccount(0)
        const claimResult = await account0.claimStaticDeposit(CLAIM_TX_ID)
        console.log(`   ✅ Deposit claimed successfully!`)
        console.log(`   Result:`, claimResult)
        
        // Check updated balance
        const newBalance = await account0.getBalance()
        const balanceValue = typeof newBalance === 'object'
          ? (newBalance.confirmed || newBalance.total || newBalance.available || 0)
          : (newBalance || 0)
        console.log(`   💰 New balance: ${balanceValue} sats`)
      } catch (claimError) {
        console.error(`   ❌ Failed to claim deposit:`, claimError)
        console.log(`   💡 Make sure the transaction is confirmed on the Bitcoin network`)
        console.log(`   💡 Transaction ID format should be: 64-character hex string`)
      }
      console.log("")
    }
    
    // Step 3: Test multiple account indices
    console.log("\n3️⃣  Testing Spark account indices...")
    console.log("   Testing if Spark supports multiple accounts (index 0 vs index 1)...")
    
    const account0 = await wdkManager.getSparkAccount(0)
    const address0 = await account0.getAddress()
    console.log(`   ✅ Account 0 (Customer): ${address0}`)
    
    const account1 = await wdkManager.getSparkAccount(1)
    const address1 = await account1.getAddress()
    console.log(`   ✅ Account 1 (Shop):     ${address1}`)
    
    if (address0 === address1) {
      console.log(`   ⚠️  SAME ADDRESS! Spark does NOT support multiple indices`)
      console.log(`   💡 Will need separate seed phrases for customer & shop`)
    } else {
      console.log(`   ✅ DIFFERENT ADDRESSES! Spark supports multiple indices`)
      console.log(`   ✅ Customer and shop can have separate wallets`)
    }
    
    // Use account 0 for remaining tests
    const address = address0
    console.log(`\n   Using Account 0 for remaining tests...`)

    // Step 4: Check balance
    console.log("\n4️⃣  Checking Spark balance...")
    const balance = await lightningProcessor.getBalance()
    console.log(`   ✅ Balance: ${balance.btc.toFixed(8)} BTC`)
    console.log(`   ✅ Balance: ${Number(balance.sats)} sats`)

    // Step 5: Shop generates Lightning invoice (index 1)
    console.log("\n5️⃣  Shop generating Lightning Network invoice...")
    const testAmountSats = 1000 // 1000 sats (~$1 at $100k/BTC)
    const shopAccount = await wdkManager.getSparkAccount(1) // SHOP wallet (index 1)
    const invoiceData = await shopAccount.createLightningInvoice({
      amountSats: testAmountSats,
      memo: 'Test Coffee Order - Large Latte',
    })
    
    console.log(`   ✅ Invoice generated by SHOP (index 1)`)
    console.log(`   Amount: ${testAmountSats} sats`)
    console.log(`   Shop address: ${await shopAccount.getAddress()}`)
    
    // Debug: Log the full invoice data structure
    console.log(`   📋 Invoice data structure:`, JSON.stringify(invoiceData, null, 2))
    
    // Handle different invoice formats from Spark SDK
    let invoiceString: string | undefined
    
    if (typeof invoiceData === 'string') {
      invoiceString = invoiceData
    } else if (typeof invoiceData.invoice === 'string') {
      invoiceString = invoiceData.invoice
    } else if (typeof invoiceData.encodedInvoice === 'string') {
      invoiceString = invoiceData.encodedInvoice
    } else if (typeof invoiceData.invoice?.encodedInvoice === 'string') {
      invoiceString = invoiceData.invoice.encodedInvoice
    } else if (typeof invoiceData.paymentRequest === 'string') {
      invoiceString = invoiceData.paymentRequest
    } else if (typeof invoiceData.bolt11 === 'string') {
      invoiceString = invoiceData.bolt11
    }
    
    if (!invoiceString || typeof invoiceString !== 'string') {
      console.error(`   ❌ Could not extract valid invoice string from response`)
      console.error(`   Available keys:`, Object.keys(invoiceData))
      throw new Error('Invalid invoice format - no valid string found')
    }
    
    console.log(`   Invoice type: ${typeof invoiceString}`)
    console.log(`   Invoice: ${invoiceString.substring(0, 50)}...`)

    // Step 6: Customer pays the shop's invoice (index 0 → index 1)
    console.log("\n6️⃣  Customer paying shop's Lightning invoice...")
    console.log(`   💸 Payment flow: Customer (index 0) → Shop (index 1)`)
    try {
      const customerAccount = await wdkManager.getSparkAccount(0) // CUSTOMER wallet (index 0)
      const customerBalance = await customerAccount.getBalance()
      console.log(`   Customer balance: ${customerBalance} sats`)
      console.log(`   Customer address: ${await customerAccount.getAddress()}`)
      
      // Validate invoice string before proceeding
      if (!invoiceString || typeof invoiceString !== 'string') {
        throw new Error('Invoice string is not valid')
      }
      
      console.log(`   🔍 Validating invoice: ${invoiceString.substring(0, 20)}... (length: ${invoiceString.length})`)
      
      // Get fee estimate first
      let feeEstimate = 0
      try {
        const feeQuote = await customerAccount.quotePayLightningInvoice({
          encodedInvoice: invoiceString // SDK expects 'invoice', not 'encodedInvoice'
        })
        feeEstimate = Number(feeQuote)
        console.log(`   💰 Fee estimate: ${feeEstimate} sats`)
      } catch (feeError) {
        console.log(`   ⚠️  Could not get fee estimate, using default: ${feeError instanceof Error ? feeError.message : String(feeError)}`)
        feeEstimate = 100 // Default fee buffer
      }
      
      const requiredBalance = testAmountSats + feeEstimate + 100 // Amount + fee + buffer
      console.log(`   Required balance: ${requiredBalance} sats (${testAmountSats} amount + ${feeEstimate} fee + 100 buffer)`)
      
      if (customerBalance >= requiredBalance) {
        console.log(`   ✅ Sufficient balance for payment`)
        console.log(`   Invoice to pay: ${invoiceString.substring(0, 30)}...`)
        
        console.log(`   🔍 DEBUG: Calling payLightningInvoice with:`)
        console.log(`      - invoice type: ${typeof invoiceString}`)
        console.log(`      - invoice value: ${invoiceString.substring(0, 50)}...`)
        console.log(`      - maxFeeSats: ${feeEstimate + 100}`)

        
        const payment = await customerAccount.payLightningInvoice({
          invoice: invoiceString, // SDK expects 'invoice', not 'encodedInvoice'
          maxFeeSats: feeEstimate + 100, // Fee estimate + buffer

        })
        console.log(`   ✅ Payment initiated!`)
        console.log(`   Payment ID: ${payment.id}`)
        
        // Poll for payment completion
        console.log(`   ⏳ Checking payment status...`)
        let paymentComplete = false
        let attempts = 0
        const maxAttempts = 10
        
        while (!paymentComplete && attempts < maxAttempts) {
          await new Promise(resolve => setTimeout(resolve, 1000))
          attempts++
          
          try {
            const sendRequest = await customerAccount.getLightningSendRequest(payment.id)
            if (sendRequest) {
              console.log(`   [${attempts}/${maxAttempts}] Status: ${sendRequest.status}`)
              
              // Check if payment is complete (success or failure)
              if (sendRequest.status === 'TRANSFER_COMPLETED' || 
                  sendRequest.status === 'LIGHTNING_PAYMENT_SUCCEEDED') {
                console.log(`   ✅ Payment COMPLETED!`)
                if (sendRequest.paymentPreimage) {
                  console.log(`   🔑 Preimage: ${sendRequest.paymentPreimage.substring(0, 20)}...`)
                }
                paymentComplete = true
                break
              } else if (sendRequest.status === 'TRANSFER_FAILED' ||
                         sendRequest.status === 'LIGHTNING_PAYMENT_FAILED' ||
                         sendRequest.status === 'USER_TRANSFER_VALIDATION_FAILED') {
                console.log(`   ❌ Payment FAILED: ${sendRequest.status}`)
                paymentComplete = true
                break
              }
            }
          } catch (statusError) {
            console.log(`   ⚠️  Could not check status: ${statusError instanceof Error ? statusError.message : String(statusError)}`)
            break
          }
        }
        
        if (!paymentComplete) {
          console.log(`   ⏳ Payment still processing after ${maxAttempts} seconds`)
        }
      } else {
        console.log(`   ⚠️  Insufficient balance!`)
        console.log(`   💡 Customer wallet has ${customerBalance} sats, needs ${requiredBalance} sats`)
        console.log(`   💡 Breakdown: ${testAmountSats} (payment) + ${feeEstimate} (fee) + 100 (buffer)`)
        console.log(`   Skipping payment test...`)
      }
    } catch (error) {
      console.log(`   ⚠️  Could not pay invoice: ${error instanceof Error ? error.message : String(error)}`)
      
      console.log(`   💡 This may indicate:`)
      console.log(`      - Invoice doesn't include Spark fallback address`)
      console.log(`      - Network connectivity issues`)
      console.log(`      - Try TESTNET for full Lightning routing tests`)
    }

    // Step 7: Verify both wallets after payment
    console.log("\n7️⃣  Verifying wallet balances after payment...")
    try {
      // Check customer balance
      const customerAccount = await wdkManager.getSparkAccount(0)
      const customerBalanceAfter = await customerAccount.getBalance()
      console.log(`   Customer (index 0) balance: ${customerBalanceAfter} sats`)
      
      // Check shop balance
      const shopAccount = await wdkManager.getSparkAccount(1)
      const shopBalance = await shopAccount.getBalance()
      console.log(`   Shop (index 1) balance:     ${shopBalance} sats`)
      
      if (shopBalance >= testAmountSats) {
        console.log(`   🎉 Shop successfully received Lightning payment!`)
        console.log(`   ✅ Payment flow verified: Customer → Shop`)
      } else if (shopBalance > 0) {
        console.log(`   ⚠️  Shop has some balance, but less than expected payment`)
      } else {
        console.log(`   ℹ️  Shop balance is 0 (payment may not have settled on REGTEST)`)
      }
    } catch (error) {
      console.log(`   ⚠️  Could not check balances: ${error instanceof Error ? error.message : String(error)}`)
    }

    // Step 8: Get transaction history
    console.log("\n8️⃣  Fetching transaction history...")
    const transfers = await lightningProcessor.getTransfers({ limit: 5 })
    console.log(`   ✅ Found ${transfers.length} recent transfers`)
    if (transfers.length > 0) {
      transfers.forEach((t, i) => {
        console.log(`   ${i + 1}. ${t.type}: ${t.amount} sats - ${t.timestamp.toLocaleString()}`)
      })
    } else {
      console.log(`   No transfers found yet`)
    }

    // Step 9: Get Bitcoin L1 deposit address and check for pending deposits
    console.log("\n9️⃣  Getting Bitcoin L1 deposit address...")
    const depositAddress = await lightningProcessor.getDepositAddress()
    console.log(`   ✅ Deposit Address: ${depositAddress}`)
    console.log(`   💡 Send Bitcoin to this address to fund your Spark wallet`)
    
    // Check for unused/pending deposits
    console.log("\n🔍 Checking for pending deposits...")
    try {
      const account0 = await wdkManager.getSparkAccount(0)
      const unusedDeposits = await account0.getUnusedDepositAddresses()
      console.log(`   Unused deposit addresses: ${unusedDeposits.length}`)
      
      if (unusedDeposits.length > 0) {
        console.log(`   ⏳ You may have pending deposits that need to be claimed`)
        console.log(`   💡 If you sent BTC, you need to claim it with the transaction ID`)
      }
    } catch (err) {
      console.log(`   ⚠️  Could not check unused deposits: ${err instanceof Error ? err.message : String(err)}`)
    }

    // Summary
    console.log("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    console.log("📊 LIGHTNING NETWORK STATUS:")
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    console.log("✅ Spark wallets initialized (HD derivation working)")
    console.log(`\n👤 Customer Wallet (index 0):`)
    console.log(`   Address: ${address0}`)
    console.log(`   Balance: ${balance.btc.toFixed(8)} BTC (${Number(balance.sats)} sats)`)
    console.log(`\n🏪 Shop Wallet (index 1):`)
    console.log(`   Address: ${address1}`)
    try {
      const shopAccount = await wdkManager.getSparkAccount(1)
      const shopBalance = await shopAccount.getBalance()
      const shopBalanceValue = typeof shopBalance === 'object' && shopBalance !== null
        ? (shopBalance.confirmed || shopBalance.total || shopBalance.available || 0)
        : (shopBalance || 0)
      console.log(`   Balance: ${(Number(shopBalanceValue) / 1e8).toFixed(8)} BTC (${shopBalanceValue} sats)`)
    } catch (err) {
      console.log(`   Balance: Unable to fetch`)
    }
    console.log(`\n✅ Lightning invoices: Working`)
    console.log(`✅ Payment flow: Customer (0) → Shop (1)`)
    
    console.log(`   💡 On REGTEST: Uses Spark fallback address for instant transfers`)
    console.log(`   💡 On TESTNET/MAINNET: Can use real Lightning routing`)
    console.log(`✅ Compatible with ANY Lightning wallet (Trust Wallet, Blue Wallet, etc.)`)
    
    if (Number(balance.sats) > 0) {
      console.log("\n✅ Lightning Network is READY!")
      console.log("✅ You can accept instant BTC payments for coffee orders")
    } else {
      console.log("\n⚠️  CUSTOMER WALLET IS EMPTY!")
      console.log("\n📍 How to fund your customer Spark wallet (index 0):")
      console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
      console.log(`1. Copy your deposit address: ${depositAddress}`)
      console.log("2. Send Bitcoin to this address (REGTEST/testnet/mainnet)")
      console.log("3. Wait for confirmation (1-6 blocks depending on network)")
      console.log("4. Claim the deposit:")
      console.log("   - Get your transaction ID from the Bitcoin wallet")
      console.log("   - Run: CLAIM_TX_ID=your_tx_id bun run test:lightning")
      console.log("   - Or manually: account.claimStaticDeposit(txId)")
      console.log("\n💡 For instant testing, switch to TESTNET:")
      console.log("   - Set SPARK_NETWORK=TESTNET in .env")
      console.log("   - Get free testnet BTC from faucets")
      console.log("   - Test full Lightning payment flow")
    }
    
    console.log("\n💡 Next Steps:")
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    console.log("1. Fund your Spark wallet (if empty)")
    console.log("2. Test payment flow: bun run ui")
    console.log("3. Place a coffee order and pay with Lightning")
    console.log("4. Verify instant confirmation (< 1 second)")
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

  } catch (error) {
    console.error(`\n❌ Error testing Lightning Network: ${error instanceof Error ? error.message : String(error)}`)
    console.log("\n💡 Troubleshooting:")
    console.log("   • Ensure Spark wallet is properly initialized")
    console.log("   • Check network connectivity")
    console.log("   • Verify SPARK_NETWORK environment variable")
    console.log("   • Check if you're on testnet or mainnet")
  } finally {
    if (lightningProcessor) {
      lightningProcessor.dispose()
    }
  }
}

// Run the test
testLightningNetwork().catch(console.error)

